export const allModels = {
	Banner_01: {
		path: '/content-browser/models/Banner_01.glb',
		thumbnail: '/content-browser/models/Banner_01.png',
		displayName: 'Banner',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, 0, 0],
	},
	Castle_Wall_01: {
		path: '/content-browser/models/Castle_Wall_01.glb',
		thumbnail: '/content-browser/models/Castle_Wall_01.png',
		displayName: 'Castle Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Arch_01: {
		path: '/content-browser/models/Grey_Arch_01.glb',
		thumbnail: '/content-browser/models/Grey_Arch_01.png',
		displayName: 'Grey Arch',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Border_Wall_01: {
		path: '/content-browser/models/Grey_Border_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Border_Wall_01.png',
		displayName: 'Grey Border Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Broken_Wall_01: {
		path: '/content-browser/models/Grey_Broken_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Broken_Wall_01.png',
		displayName: 'Grey Broken Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Corner_01: {
		path: '/content-browser/models/Grey_Corner_01.glb',
		thumbnail: '/content-browser/models/Grey_Corner_01.png',
		displayName: 'Grey Corner',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Door_Round_01: {
		path: '/content-browser/models/Grey_Door_Round_01.glb',
		thumbnail: '/content-browser/models/Grey_Door_Round_01.png',
		displayName: 'Grey Door Round',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Door_Square_01: {
		path: '/content-browser/models/Grey_Door_Square_01.glb',
		thumbnail: '/content-browser/models/Grey_Door_Square_01.png',
		displayName: 'Grey Door Square',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Pole_01: {
		path: '/content-browser/models/Grey_Pole_01.glb',
		thumbnail: '/content-browser/models/Grey_Pole_01.png',
		displayName: 'Grey Pole',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Short_Wall_01: {
		path: '/content-browser/models/Grey_Short_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Short_Wall_01.png',
		displayName: 'Grey Short Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Slanted_Pole_01: {
		path: '/content-browser/models/Grey_Slanted_Pole_01.glb',
		thumbnail: '/content-browser/models/Grey_Slanted_Pole_01.png',
		displayName: 'Grey Slanted Pole',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Slanted_Wall_01: {
		path: '/content-browser/models/Grey_Slanted_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Slanted_Wall_01.png',
		displayName: 'Grey Slanted Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Small_Wall_01: {
		path: '/content-browser/models/Grey_Small_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Small_Wall_01.png',
		displayName: 'Grey Small Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Triangle_01: {
		path: '/content-browser/models/Grey_Triangle_01.glb',
		thumbnail: '/content-browser/models/Grey_Triangle_01.png',
		displayName: 'Grey Triangle',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Wall_01: {
		path: '/content-browser/models/Grey_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Wall_01.png',
		displayName: 'Grey Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Narrow_01: {
		path: '/content-browser/models/Grey_Window_Narrow_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Narrow_01.png',
		displayName: 'Grey Window Narrow',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Round_01: {
		path: '/content-browser/models/Grey_Window_Round_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Round_01.png',
		displayName: 'Grey Window Round',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Round_Long_01: {
		path: '/content-browser/models/Grey_Window_Round_Long_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Round_Long_01.png',
		displayName: 'Grey Window Round Long',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Square_01: {
		path: '/content-browser/models/Grey_Window_Square_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Square_01.png',
		displayName: 'Grey Window Square',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Square_Sill_01: {
		path: '/content-browser/models/Grey_Window_Square_Sill_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Square_Sill_01.png',
		displayName: 'Grey Window Square Sill',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Iron_Door_01: {
		path: '/content-browser/models/Iron_Door_01.glb',
		thumbnail: '/content-browser/models/Iron_Door_01.png',
		displayName: 'Iron Door',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Lightpost_01: {
		path: '/content-browser/models/Lightpost_01.glb',
		thumbnail: '/content-browser/models/Lightpost_01.png',
		displayName: 'Lightpost',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Corner_01: {
		path: '/content-browser/models/Plate_Corner_01.glb',
		thumbnail: '/content-browser/models/Plate_Corner_01.png',
		displayName: 'Plate Corner',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Curve_01: {
		path: '/content-browser/models/Plate_Curve_01.glb',
		thumbnail: '/content-browser/models/Plate_Curve_01.png',
		displayName: 'Plate Curve',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Pavement_01: {
		path: '/content-browser/models/Plate_Pavement_01.glb',
		thumbnail: '/content-browser/models/Plate_Pavement_01.png',
		displayName: 'Plate Pavement',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Road_01: {
		path: '/content-browser/models/Plate_Road_01.glb',
		thumbnail: '/content-browser/models/Plate_Road_01.png',
		displayName: 'Plate Road',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Sidewalk_01: {
		path: '/content-browser/models/Plate_Sidewalk_01.glb',
		thumbnail: '/content-browser/models/Plate_Sidewalk_01.png',
		displayName: 'Plate Sidewalk',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Wood_01: {
		path: '/content-browser/models/Plate_Wood_01.glb',
		thumbnail: '/content-browser/models/Plate_Wood_01.png',
		displayName: 'Plate Wood',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Inner_Corner_Green_01: {
		path: '/content-browser/models/Roof_Inner_Corner_Green_01.glb',
		thumbnail: '/content-browser/models/Roof_Inner_Corner_Green_01.png',
		displayName: 'Roof Inner Corner Green',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Inner_Corner_Red_01: {
		path: '/content-browser/models/Roof_Inner_Corner_Red_01.glb',
		thumbnail: '/content-browser/models/Roof_Inner_Corner_Red_01.png',
		displayName: 'Roof Inner Corner Red',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Point_Green_01: {
		path: '/content-browser/models/Roof_Point_Green_01.glb',
		thumbnail: '/content-browser/models/Roof_Point_Green_01.png',
		displayName: 'Roof Point Green',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Point_Red_01: {
		path: '/content-browser/models/Roof_Point_Red_01.glb',
		thumbnail: '/content-browser/models/Roof_Point_Red_01.png',
		displayName: 'Roof Point Red',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Slant_Green_01: {
		path: '/content-browser/models/Roof_Slant_Green_01.glb',
		thumbnail: '/content-browser/models/Roof_Slant_Green_01.png',
		displayName: 'Roof Slant Green',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Slant_Red_01: {
		path: '/content-browser/models/Roof_Slant_Red_01.glb',
		thumbnail: '/content-browser/models/Roof_Slant_Red_01.png',
		displayName: 'Roof Slant Red',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Straight_Green_01: {
		path: '/content-browser/models/Roof_Straight_Green_01.glb',
		thumbnail: '/content-browser/models/Roof_Straight_Green_01.png',
		displayName: 'Roof Straight Green',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Straight_Red_01: {
		path: '/content-browser/models/Roof_Straight_Red_01.glb',
		thumbnail: '/content-browser/models/Roof_Straight_Red_01.png',
		displayName: 'Roof Straight Red',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Shield_Green_01: {
		path: '/content-browser/models/Shield_Green_01.glb',
		thumbnail: '/content-browser/models/Shield_Green_01.png',
		displayName: 'Shield Green',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Shield_Red_01: {
		path: '/content-browser/models/Shield_Red_01.glb',
		thumbnail: '/content-browser/models/Shield_Red_01.png',
		displayName: 'Shield Red',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Stairs_Stone_01: {
		path: '/content-browser/models/Stairs_Stone_01.glb',
		thumbnail: '/content-browser/models/Stairs_Stone_01.png',
		displayName: 'Stairs Stone',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Stairs_Wood_01: {
		path: '/content-browser/models/Stairs_Wood_01.glb',
		thumbnail: '/content-browser/models/Stairs_Wood_01.png',
		displayName: 'Stairs Wood',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Tree_01: {
		path: '/content-browser/models/Tree_01.glb',
		thumbnail: '/content-browser/models/Tree_01.png',
		displayName: 'Tree',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Arch_01: {
		path: '/content-browser/models/Wood_Arch_01.glb',
		thumbnail: '/content-browser/models/Wood_Arch_01.png',
		displayName: 'Wood Arch',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Border_Wall_01: {
		path: '/content-browser/models/Wood_Border_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Border_Wall_01.png',
		displayName: 'Wood Border Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Broken_Wall_01: {
		path: '/content-browser/models/Wood_Broken_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Broken_Wall_01.png',
		displayName: 'Wood Broken Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Corner_01: {
		path: '/content-browser/models/Wood_Corner_01.glb',
		thumbnail: '/content-browser/models/Wood_Corner_01.png',
		displayName: 'Wood Corner',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Door_01: {
		path: '/content-browser/models/Wood_Door_01.glb',
		thumbnail: '/content-browser/models/Wood_Door_01.png',
		displayName: 'Wood Door',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Door_Round_01: {
		path: '/content-browser/models/Wood_Door_Round_01.glb',
		thumbnail: '/content-browser/models/Wood_Door_Round_01.png',
		displayName: 'Wood Door Round',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Door_Square_01: {
		path: '/content-browser/models/Wood_Door_Square_01.glb',
		thumbnail: '/content-browser/models/Wood_Door_Square_01.png',
		displayName: 'Wood Door Square',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Pole_01: {
		path: '/content-browser/models/Wood_Pole_01.glb',
		thumbnail: '/content-browser/models/Wood_Pole_01.png',
		displayName: 'Wood Pole',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Railing_01: {
		path: '/content-browser/models/Wood_Railing_01.glb',
		thumbnail: '/content-browser/models/Wood_Railing_01.png',
		displayName: 'Wood Railing',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Slanted_Pole_01: {
		path: '/content-browser/models/Wood_Slanted_Pole_01.glb',
		thumbnail: '/content-browser/models/Wood_Slanted_Pole_01.png',
		displayName: 'Wood Slanted Pole',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Slanted_Wall_01: {
		path: '/content-browser/models/Wood_Slanted_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Slanted_Wall_01.png',
		displayName: 'Wood Slanted Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Small_Wall_01: {
		path: '/content-browser/models/Wood_Small_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Small_Wall_01.png',
		displayName: 'Wood Small Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Tiny_Wall_01: {
		path: '/content-browser/models/Wood_Tiny_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Tiny_Wall_01.png',
		displayName: 'Wood Tiny Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Triangle_01: {
		path: '/content-browser/models/Wood_Triangle_01.glb',
		thumbnail: '/content-browser/models/Wood_Triangle_01.png',
		displayName: 'Wood Triangle',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Wall_01: {
		path: '/content-browser/models/Wood_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Wall_01.png',
		displayName: 'Wood Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Wall_Cross_01: {
		path: '/content-browser/models/Wood_Wall_Cross_01.glb',
		thumbnail: '/content-browser/models/Wood_Wall_Cross_01.png',
		displayName: 'Wood Wall Cross',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Wall_Double_Cross_01: {
		path: '/content-browser/models/Wood_Wall_Double_Cross_01.glb',
		thumbnail: '/content-browser/models/Wood_Wall_Double_Cross_01.png',
		displayName: 'Wood Wall Double Cross',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Narrow_01: {
		path: '/content-browser/models/Wood_Window_Narrow_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Narrow_01.png',
		displayName: 'Wood Window Narrow',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Round_01: {
		path: '/content-browser/models/Wood_Window_Round_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Round_01.png',
		displayName: 'Wood Window Round',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Round_Long_01: {
		path: '/content-browser/models/Wood_Window_Round_Long_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Round_Long_01.png',
		displayName: 'Wood Window Round Long',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Round_Sill_01: {
		path: '/content-browser/models/Wood_Window_Round_Sill_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Round_Sill_01.png',
		displayName: 'Wood Window Round Sill',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Square_01: {
		path: '/content-browser/models/Wood_Window_Square_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Square_01.png',
		displayName: 'Wood Window Square',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Square_Sill_01: {
		path: '/content-browser/models/Wood_Window_Square_Sill_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Square_Sill_01.png',
		displayName: 'Wood Window Square Sill',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},

	detail_awning: {
		path: '/content-browser/city/detail_awning.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Detail Awning',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	detail_awningWide: {
		path: '/content-browser/city/detail_awningWide.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Detail AwningWide',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	detail_overhang: {
		path: '/content-browser/city/detail_overhang.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Detail Overhang',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	detail_overhangWide: {
		path: '/content-browser/city/detail_overhangWide.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Detail OverhangWide',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	detail_umbrella: {
		path: '/content-browser/city/detail_umbrella.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Detail Umbrella',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	detail_umbrellaDetailed: {
		path: '/content-browser/city/detail_umbrellaDetailed.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Detail UmbrellaDetailed',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	large_buildingA: {
		path: '/content-browser/city/large_buildingA.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Large BuildingA',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	large_buildingB: {
		path: '/content-browser/city/large_buildingB.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Large BuildingB',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	large_buildingC: {
		path: '/content-browser/city/large_buildingC.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Large BuildingC',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	large_buildingD: {
		path: '/content-browser/city/large_buildingD.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Large BuildingD',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	large_buildingE: {
		path: '/content-browser/city/large_buildingE.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Large BuildingE',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	large_buildingF: {
		path: '/content-browser/city/large_buildingF.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Large BuildingF',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	large_buildingG: {
		path: '/content-browser/city/large_buildingG.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Large BuildingG',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingA: {
		path: '/content-browser/city/low_buildingA.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingA',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingB: {
		path: '/content-browser/city/low_buildingB.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingB',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingC: {
		path: '/content-browser/city/low_buildingC.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingC',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingD: {
		path: '/content-browser/city/low_buildingD.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingD',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingE: {
		path: '/content-browser/city/low_buildingE.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingE',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingF: {
		path: '/content-browser/city/low_buildingF.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingF',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingG: {
		path: '/content-browser/city/low_buildingG.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingG',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingH: {
		path: '/content-browser/city/low_buildingH.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingH',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingI: {
		path: '/content-browser/city/low_buildingI.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingI',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingJ: {
		path: '/content-browser/city/low_buildingJ.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingJ',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingK: {
		path: '/content-browser/city/low_buildingK.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingK',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingL: {
		path: '/content-browser/city/low_buildingL.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingL',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingM: {
		path: '/content-browser/city/low_buildingM.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingM',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_buildingN: {
		path: '/content-browser/city/low_buildingN.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low BuildingN',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_wideA: {
		path: '/content-browser/city/low_wideA.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low WideA',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	low_wideB: {
		path: '/content-browser/city/low_wideB.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Low WideB',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	roof_center: {
		path: '/content-browser/city/roof_center.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Roof Center',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	roof_corner: {
		path: '/content-browser/city/roof_corner.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Roof Corner',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	roof_overhang: {
		path: '/content-browser/city/roof_overhang.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Roof Overhang',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	roof_side: {
		path: '/content-browser/city/roof_side.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Roof Side',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	sign_billboard: {
		path: '/content-browser/city/sign_billboard.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Sign Billboard',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	sign_hospital: {
		path: '/content-browser/city/sign_hospital.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Sign Hospital',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	skyscraperA: {
		path: '/content-browser/city/skyscraperA.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'SkyscraperA',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	skyscraperB: {
		path: '/content-browser/city/skyscraperB.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'SkyscraperB',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	skyscraperC: {
		path: '/content-browser/city/skyscraperC.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'SkyscraperC',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	skyscraperD: {
		path: '/content-browser/city/skyscraperD.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'SkyscraperD',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	skyscraperE: {
		path: '/content-browser/city/skyscraperE.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'SkyscraperE',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	skyscraperF: {
		path: '/content-browser/city/skyscraperF.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'SkyscraperF',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	small_buildingA: {
		path: '/content-browser/city/small_buildingA.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Small BuildingA',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	small_buildingB: {
		path: '/content-browser/city/small_buildingB.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Small BuildingB',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	small_buildingC: {
		path: '/content-browser/city/small_buildingC.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Small BuildingC',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	small_buildingD: {
		path: '/content-browser/city/small_buildingD.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Small BuildingD',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	small_buildingE: {
		path: '/content-browser/city/small_buildingE.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Small BuildingE',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	small_buildingF: {
		path: '/content-browser/city/small_buildingF.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Small BuildingF',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_doorA: {
		path: '/content-browser/city/wall_doorA.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall DoorA',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_doorB: {
		path: '/content-browser/city/wall_doorB.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall DoorB',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_solid: {
		path: '/content-browser/city/wall_solid.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall Solid',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_windowA: {
		path: '/content-browser/city/wall_windowA.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall WindowA',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_windowB: {
		path: '/content-browser/city/wall_windowB.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall WindowB',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_windowC: {
		path: '/content-browser/city/wall_windowC.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall WindowC',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_windowD: {
		path: '/content-browser/city/wall_windowD.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall WindowD',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_windowE: {
		path: '/content-browser/city/wall_windowE.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall WindowE',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
	wall_windowF: {
		path: '/content-browser/city/wall_windowF.glb',
		thumbnail: '/content-browser/city/large_buildingA.png',
		displayName: 'Wall WindowF',
		type: 'model',
		modelType: 'city',
		hudModelRot: [0, 0, 0],
	},
}

export const allShapes = {
	box: {
		thumbnail: '/content-browser/shapes/box.svg',
		displayName: 'Box',
		type: 'shape',
	},
	sphere: {
		thumbnail: '/content-browser/shapes/sphere.svg',
		displayName: 'Sphere',
		type: 'shape',
	},
	cone: {
		thumbnail: '/content-browser/shapes/cone.svg',
		displayName: 'Cone',
		type: 'shape',
	},
	cylinder: {
		thumbnail: '/content-browser/shapes/cylinder.svg',
		displayName: 'Cylinder',
		type: 'shape',
	},
	octahedron: {
		thumbnail: '/content-browser/shapes/octahedron.svg',
		displayName: 'Octahedron',
		type: 'shape',
	},
	icosahedron: {
		thumbnail: '/content-browser/shapes/icosahedron.svg',
		displayName: 'Icosahedron',
		type: 'shape',
	},
}
