export const allModels = {
	Chase_Tower_01: {
		path: '/content-browser/models/chase_tower.glb',
		thumbnail: '/content-browser/shapes/box.svg',
		displayName: 'Chase Tower 2mb',
		type: 'model',
		modelType: 'test',
		hudModelRot: [0, 0, 0],
	},
	Lighthouse_01: {
		path: '/content-browser/models/lighthouse.glb',
		thumbnail: '/content-browser/shapes/box.svg',
		displayName: 'Lighthouse 6.8mb',
		type: 'model',
		modelType: 'test',
		hudModelRot: [0, 0, 0],
	},
	Fantasy_Town_01: {
		path: '/content-browser/models/fantasy_town.glb',
		thumbnail: '/content-browser/shapes/box.svg',
		displayName: 'Fantasy Town 7.4mb',
		type: 'model',
		modelType: 'test',
		hudModelRot: [0, 0, 0],
	},
	Kickelhahn_Tower_01: {
		path: '/content-browser/models/kickelhahn_tower_scaled.glb',
		thumbnail: '/content-browser/shapes/sphere.svg',
		displayName: 'Kickelhahn Tower 7.2mb',
		type: 'model',
		modelType: 'test',
		hudModelRot: [0, 0, 0],
	},
	Tall_Building_01: {
		path: '/content-browser/models/tall_building_scaled.glb',
		thumbnail: '/content-browser/shapes/box.svg',
		displayName: 'Tall Building 27.9mb',
		type: 'model',
		modelType: 'test',
		hudModelRot: [0, 0, 0],
	},
	Banner_01: {
		path: '/content-browser/models/Banner_01.glb',
		thumbnail: '/content-browser/models/Banner_01.png',
		displayName: 'Banner',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, 0, 0],
	},
	Castle_Wall_01: {
		path: '/content-browser/models/Castle_Wall_01.glb',
		thumbnail: '/content-browser/models/Castle_Wall_01.png',
		displayName: 'Castle Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Arch_01: {
		path: '/content-browser/models/Grey_Arch_01.glb',
		thumbnail: '/content-browser/models/Grey_Arch_01.png',
		displayName: 'Grey Arch',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Border_Wall_01: {
		path: '/content-browser/models/Grey_Border_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Border_Wall_01.png',
		displayName: 'Grey Border Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Broken_Wall_01: {
		path: '/content-browser/models/Grey_Broken_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Broken_Wall_01.png',
		displayName: 'Grey Broken Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Corner_01: {
		path: '/content-browser/models/Grey_Corner_01.glb',
		thumbnail: '/content-browser/models/Grey_Corner_01.png',
		displayName: 'Grey Corner',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Door_Round_01: {
		path: '/content-browser/models/Grey_Door_Round_01.glb',
		thumbnail: '/content-browser/models/Grey_Door_Round_01.png',
		displayName: 'Grey Door Round',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Door_Square_01: {
		path: '/content-browser/models/Grey_Door_Square_01.glb',
		thumbnail: '/content-browser/models/Grey_Door_Square_01.png',
		displayName: 'Grey Door Square',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Pole_01: {
		path: '/content-browser/models/Grey_Pole_01.glb',
		thumbnail: '/content-browser/models/Grey_Pole_01.png',
		displayName: 'Grey Pole',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Short_Wall_01: {
		path: '/content-browser/models/Grey_Short_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Short_Wall_01.png',
		displayName: 'Grey Short Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Slanted_Pole_01: {
		path: '/content-browser/models/Grey_Slanted_Pole_01.glb',
		thumbnail: '/content-browser/models/Grey_Slanted_Pole_01.png',
		displayName: 'Grey Slanted Pole',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Slanted_Wall_01: {
		path: '/content-browser/models/Grey_Slanted_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Slanted_Wall_01.png',
		displayName: 'Grey Slanted Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Small_Wall_01: {
		path: '/content-browser/models/Grey_Small_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Small_Wall_01.png',
		displayName: 'Grey Small Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Triangle_01: {
		path: '/content-browser/models/Grey_Triangle_01.glb',
		thumbnail: '/content-browser/models/Grey_Triangle_01.png',
		displayName: 'Grey Triangle',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Wall_01: {
		path: '/content-browser/models/Grey_Wall_01.glb',
		thumbnail: '/content-browser/models/Grey_Wall_01.png',
		displayName: 'Grey Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Narrow_01: {
		path: '/content-browser/models/Grey_Window_Narrow_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Narrow_01.png',
		displayName: 'Grey Window Narrow',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Round_01: {
		path: '/content-browser/models/Grey_Window_Round_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Round_01.png',
		displayName: 'Grey Window Round',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Round_Long_01: {
		path: '/content-browser/models/Grey_Window_Round_Long_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Round_Long_01.png',
		displayName: 'Grey Window Round Long',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Square_01: {
		path: '/content-browser/models/Grey_Window_Square_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Square_01.png',
		displayName: 'Grey Window Square',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Grey_Window_Square_Sill_01: {
		path: '/content-browser/models/Grey_Window_Square_Sill_01.glb',
		thumbnail: '/content-browser/models/Grey_Window_Square_Sill_01.png',
		displayName: 'Grey Window Square Sill',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Iron_Door_01: {
		path: '/content-browser/models/Iron_Door_01.glb',
		thumbnail: '/content-browser/models/Iron_Door_01.png',
		displayName: 'Iron Door',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Lightpost_01: {
		path: '/content-browser/models/Lightpost_01.glb',
		thumbnail: '/content-browser/models/Lightpost_01.png',
		displayName: 'Lightpost',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Corner_01: {
		path: '/content-browser/models/Plate_Corner_01.glb',
		thumbnail: '/content-browser/models/Plate_Corner_01.png',
		displayName: 'Plate Corner',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Curve_01: {
		path: '/content-browser/models/Plate_Curve_01.glb',
		thumbnail: '/content-browser/models/Plate_Curve_01.png',
		displayName: 'Plate Curve',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Pavement_01: {
		path: '/content-browser/models/Plate_Pavement_01.glb',
		thumbnail: '/content-browser/models/Plate_Pavement_01.png',
		displayName: 'Plate Pavement',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Road_01: {
		path: '/content-browser/models/Plate_Road_01.glb',
		thumbnail: '/content-browser/models/Plate_Road_01.png',
		displayName: 'Plate Road',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Sidewalk_01: {
		path: '/content-browser/models/Plate_Sidewalk_01.glb',
		thumbnail: '/content-browser/models/Plate_Sidewalk_01.png',
		displayName: 'Plate Sidewalk',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Plate_Wood_01: {
		path: '/content-browser/models/Plate_Wood_01.glb',
		thumbnail: '/content-browser/models/Plate_Wood_01.png',
		displayName: 'Plate Wood',
		type: 'model',
		modelType: 'floor',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Inner_Corner_Green_01: {
		path: '/content-browser/models/Roof_Inner_Corner_Green_01.glb',
		thumbnail: '/content-browser/models/Roof_Inner_Corner_Green_01.png',
		displayName: 'Roof Inner Corner Green',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Inner_Corner_Red_01: {
		path: '/content-browser/models/Roof_Inner_Corner_Red_01.glb',
		thumbnail: '/content-browser/models/Roof_Inner_Corner_Red_01.png',
		displayName: 'Roof Inner Corner Red',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Point_Green_01: {
		path: '/content-browser/models/Roof_Point_Green_01.glb',
		thumbnail: '/content-browser/models/Roof_Point_Green_01.png',
		displayName: 'Roof Point Green',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Point_Red_01: {
		path: '/content-browser/models/Roof_Point_Red_01.glb',
		thumbnail: '/content-browser/models/Roof_Point_Red_01.png',
		displayName: 'Roof Point Red',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Slant_Green_01: {
		path: '/content-browser/models/Roof_Slant_Green_01.glb',
		thumbnail: '/content-browser/models/Roof_Slant_Green_01.png',
		displayName: 'Roof Slant Green',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Slant_Red_01: {
		path: '/content-browser/models/Roof_Slant_Red_01.glb',
		thumbnail: '/content-browser/models/Roof_Slant_Red_01.png',
		displayName: 'Roof Slant Red',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Straight_Green_01: {
		path: '/content-browser/models/Roof_Straight_Green_01.glb',
		thumbnail: '/content-browser/models/Roof_Straight_Green_01.png',
		displayName: 'Roof Straight Green',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Roof_Straight_Red_01: {
		path: '/content-browser/models/Roof_Straight_Red_01.glb',
		thumbnail: '/content-browser/models/Roof_Straight_Red_01.png',
		displayName: 'Roof Straight Red',
		type: 'model',
		modelType: 'roof',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Shield_Green_01: {
		path: '/content-browser/models/Shield_Green_01.glb',
		thumbnail: '/content-browser/models/Shield_Green_01.png',
		displayName: 'Shield Green',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Shield_Red_01: {
		path: '/content-browser/models/Shield_Red_01.glb',
		thumbnail: '/content-browser/models/Shield_Red_01.png',
		displayName: 'Shield Red',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Stairs_Stone_01: {
		path: '/content-browser/models/Stairs_Stone_01.glb',
		thumbnail: '/content-browser/models/Stairs_Stone_01.png',
		displayName: 'Stairs Stone',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Stairs_Wood_01: {
		path: '/content-browser/models/Stairs_Wood_01.glb',
		thumbnail: '/content-browser/models/Stairs_Wood_01.png',
		displayName: 'Stairs Wood',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Tree_01: {
		path: '/content-browser/models/Tree_01.glb',
		thumbnail: '/content-browser/models/Tree_01.png',
		displayName: 'Tree',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Arch_01: {
		path: '/content-browser/models/Wood_Arch_01.glb',
		thumbnail: '/content-browser/models/Wood_Arch_01.png',
		displayName: 'Wood Arch',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Border_Wall_01: {
		path: '/content-browser/models/Wood_Border_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Border_Wall_01.png',
		displayName: 'Wood Border Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Broken_Wall_01: {
		path: '/content-browser/models/Wood_Broken_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Broken_Wall_01.png',
		displayName: 'Wood Broken Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Corner_01: {
		path: '/content-browser/models/Wood_Corner_01.glb',
		thumbnail: '/content-browser/models/Wood_Corner_01.png',
		displayName: 'Wood Corner',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Door_01: {
		path: '/content-browser/models/Wood_Door_01.glb',
		thumbnail: '/content-browser/models/Wood_Door_01.png',
		displayName: 'Wood Door',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Door_Round_01: {
		path: '/content-browser/models/Wood_Door_Round_01.glb',
		thumbnail: '/content-browser/models/Wood_Door_Round_01.png',
		displayName: 'Wood Door Round',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Door_Square_01: {
		path: '/content-browser/models/Wood_Door_Square_01.glb',
		thumbnail: '/content-browser/models/Wood_Door_Square_01.png',
		displayName: 'Wood Door Square',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Pole_01: {
		path: '/content-browser/models/Wood_Pole_01.glb',
		thumbnail: '/content-browser/models/Wood_Pole_01.png',
		displayName: 'Wood Pole',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Railing_01: {
		path: '/content-browser/models/Wood_Railing_01.glb',
		thumbnail: '/content-browser/models/Wood_Railing_01.png',
		displayName: 'Wood Railing',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Slanted_Pole_01: {
		path: '/content-browser/models/Wood_Slanted_Pole_01.glb',
		thumbnail: '/content-browser/models/Wood_Slanted_Pole_01.png',
		displayName: 'Wood Slanted Pole',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Slanted_Wall_01: {
		path: '/content-browser/models/Wood_Slanted_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Slanted_Wall_01.png',
		displayName: 'Wood Slanted Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Small_Wall_01: {
		path: '/content-browser/models/Wood_Small_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Small_Wall_01.png',
		displayName: 'Wood Small Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Tiny_Wall_01: {
		path: '/content-browser/models/Wood_Tiny_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Tiny_Wall_01.png',
		displayName: 'Wood Tiny Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Triangle_01: {
		path: '/content-browser/models/Wood_Triangle_01.glb',
		thumbnail: '/content-browser/models/Wood_Triangle_01.png',
		displayName: 'Wood Triangle',
		type: 'model',
		modelType: 'item',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Wall_01: {
		path: '/content-browser/models/Wood_Wall_01.glb',
		thumbnail: '/content-browser/models/Wood_Wall_01.png',
		displayName: 'Wood Wall',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Wall_Cross_01: {
		path: '/content-browser/models/Wood_Wall_Cross_01.glb',
		thumbnail: '/content-browser/models/Wood_Wall_Cross_01.png',
		displayName: 'Wood Wall Cross',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Wall_Double_Cross_01: {
		path: '/content-browser/models/Wood_Wall_Double_Cross_01.glb',
		thumbnail: '/content-browser/models/Wood_Wall_Double_Cross_01.png',
		displayName: 'Wood Wall Double Cross',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Narrow_01: {
		path: '/content-browser/models/Wood_Window_Narrow_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Narrow_01.png',
		displayName: 'Wood Window Narrow',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Round_01: {
		path: '/content-browser/models/Wood_Window_Round_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Round_01.png',
		displayName: 'Wood Window Round',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Round_Long_01: {
		path: '/content-browser/models/Wood_Window_Round_Long_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Round_Long_01.png',
		displayName: 'Wood Window Round Long',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Round_Sill_01: {
		path: '/content-browser/models/Wood_Window_Round_Sill_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Round_Sill_01.png',
		displayName: 'Wood Window Round Sill',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Square_01: {
		path: '/content-browser/models/Wood_Window_Square_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Square_01.png',
		displayName: 'Wood Window Square',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
	Wood_Window_Square_Sill_01: {
		path: '/content-browser/models/Wood_Window_Square_Sill_01.glb',
		thumbnail: '/content-browser/models/Wood_Window_Square_Sill_01.png',
		displayName: 'Wood Window Square Sill',
		type: 'model',
		modelType: 'wall',
		hudModelRot: [0, Math.PI / 2, 0],
	},
}

export const allShapes = {
	box: {
		thumbnail: '/content-browser/shapes/box.svg',
		displayName: 'Box',
		type: 'shape'
	},
	sphere: {
		thumbnail: '/content-browser/shapes/sphere.svg',
		displayName: 'Sphere',
		type: 'shape'
	},
	cone: {
		thumbnail: '/content-browser/shapes/cone.svg',
		displayName: 'Cone',
		type: 'shape'
	},
	cylinder: {
		thumbnail: '/content-browser/shapes/cylinder.svg',
		displayName: 'Cylinder',
		type: 'shape'
	},
	octahedron: {
		thumbnail: '/content-browser/shapes/octahedron.svg',
		displayName: 'Octahedron',
		type: 'shape'
	},
	icosahedron: {
		thumbnail: '/content-browser/shapes/icosahedron.svg',
		displayName: 'Icosahedron',
		type: 'shape'
	},
}
