
// Generated by generateContentBrowserItems.js

/* eslint-disable import/no-anonymous-default-export */
export default {
  "detail_awning": {
    "path": "/content-browser/city/detail_awning.glb",
    "thumbnail": "/content-browser/city/thumbnails/detail_awning.png",
    "displayName": "Detail Awning",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "detail_awningWide": {
    "path": "/content-browser/city/detail_awningWide.glb",
    "thumbnail": "/content-browser/city/thumbnails/detail_awningWide.png",
    "displayName": "Detail AwningWide",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "detail_overhang": {
    "path": "/content-browser/city/detail_overhang.glb",
    "thumbnail": "/content-browser/city/thumbnails/detail_overhang.png",
    "displayName": "Detail Overhang",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "detail_overhangWide": {
    "path": "/content-browser/city/detail_overhangWide.glb",
    "thumbnail": "/content-browser/city/thumbnails/detail_overhangWide.png",
    "displayName": "Detail OverhangWide",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "detail_umbrella": {
    "path": "/content-browser/city/detail_umbrella.glb",
    "thumbnail": "/content-browser/city/thumbnails/detail_umbrella.png",
    "displayName": "Detail Umbrella",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "detail_umbrellaDetailed": {
    "path": "/content-browser/city/detail_umbrellaDetailed.glb",
    "thumbnail": "/content-browser/city/thumbnails/detail_umbrellaDetailed.png",
    "displayName": "Detail UmbrellaDetailed",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "large_buildingA": {
    "path": "/content-browser/city/large_buildingA.glb",
    "thumbnail": "/content-browser/city/thumbnails/large_buildingA.png",
    "displayName": "Large BuildingA",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "large_buildingB": {
    "path": "/content-browser/city/large_buildingB.glb",
    "thumbnail": "/content-browser/city/thumbnails/large_buildingB.png",
    "displayName": "Large BuildingB",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "large_buildingC": {
    "path": "/content-browser/city/large_buildingC.glb",
    "thumbnail": "/content-browser/city/thumbnails/large_buildingC.png",
    "displayName": "Large BuildingC",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "large_buildingD": {
    "path": "/content-browser/city/large_buildingD.glb",
    "thumbnail": "/content-browser/city/thumbnails/large_buildingD.png",
    "displayName": "Large BuildingD",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "large_buildingE": {
    "path": "/content-browser/city/large_buildingE.glb",
    "thumbnail": "/content-browser/city/thumbnails/large_buildingE.png",
    "displayName": "Large BuildingE",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "large_buildingF": {
    "path": "/content-browser/city/large_buildingF.glb",
    "thumbnail": "/content-browser/city/thumbnails/large_buildingF.png",
    "displayName": "Large BuildingF",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "large_buildingG": {
    "path": "/content-browser/city/large_buildingG.glb",
    "thumbnail": "/content-browser/city/thumbnails/large_buildingG.png",
    "displayName": "Large BuildingG",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingA": {
    "path": "/content-browser/city/low_buildingA.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingA.png",
    "displayName": "Low BuildingA",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingB": {
    "path": "/content-browser/city/low_buildingB.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingB.png",
    "displayName": "Low BuildingB",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingC": {
    "path": "/content-browser/city/low_buildingC.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingC.png",
    "displayName": "Low BuildingC",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingD": {
    "path": "/content-browser/city/low_buildingD.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingD.png",
    "displayName": "Low BuildingD",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingE": {
    "path": "/content-browser/city/low_buildingE.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingE.png",
    "displayName": "Low BuildingE",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingF": {
    "path": "/content-browser/city/low_buildingF.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingF.png",
    "displayName": "Low BuildingF",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingG": {
    "path": "/content-browser/city/low_buildingG.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingG.png",
    "displayName": "Low BuildingG",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingH": {
    "path": "/content-browser/city/low_buildingH.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingH.png",
    "displayName": "Low BuildingH",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingI": {
    "path": "/content-browser/city/low_buildingI.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingI.png",
    "displayName": "Low BuildingI",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingJ": {
    "path": "/content-browser/city/low_buildingJ.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingJ.png",
    "displayName": "Low BuildingJ",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingK": {
    "path": "/content-browser/city/low_buildingK.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingK.png",
    "displayName": "Low BuildingK",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingL": {
    "path": "/content-browser/city/low_buildingL.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingL.png",
    "displayName": "Low BuildingL",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingM": {
    "path": "/content-browser/city/low_buildingM.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingM.png",
    "displayName": "Low BuildingM",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_buildingN": {
    "path": "/content-browser/city/low_buildingN.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_buildingN.png",
    "displayName": "Low BuildingN",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_wideA": {
    "path": "/content-browser/city/low_wideA.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_wideA.png",
    "displayName": "Low WideA",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "low_wideB": {
    "path": "/content-browser/city/low_wideB.glb",
    "thumbnail": "/content-browser/city/thumbnails/low_wideB.png",
    "displayName": "Low WideB",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "roof_center": {
    "path": "/content-browser/city/roof_center.glb",
    "thumbnail": "/content-browser/city/thumbnails/roof_center.png",
    "displayName": "Roof Center",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "roof_corner": {
    "path": "/content-browser/city/roof_corner.glb",
    "thumbnail": "/content-browser/city/thumbnails/roof_corner.png",
    "displayName": "Roof Corner",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "roof_overhang": {
    "path": "/content-browser/city/roof_overhang.glb",
    "thumbnail": "/content-browser/city/thumbnails/roof_overhang.png",
    "displayName": "Roof Overhang",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "roof_side": {
    "path": "/content-browser/city/roof_side.glb",
    "thumbnail": "/content-browser/city/thumbnails/roof_side.png",
    "displayName": "Roof Side",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "sign_billboard": {
    "path": "/content-browser/city/sign_billboard.glb",
    "thumbnail": "/content-browser/city/thumbnails/sign_billboard.png",
    "displayName": "Sign Billboard",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "sign_hospital": {
    "path": "/content-browser/city/sign_hospital.glb",
    "thumbnail": "/content-browser/city/thumbnails/sign_hospital.png",
    "displayName": "Sign Hospital",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "skyscraperA": {
    "path": "/content-browser/city/skyscraperA.glb",
    "thumbnail": "/content-browser/city/thumbnails/skyscraperA.png",
    "displayName": "SkyscraperA",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "skyscraperB": {
    "path": "/content-browser/city/skyscraperB.glb",
    "thumbnail": "/content-browser/city/thumbnails/skyscraperB.png",
    "displayName": "SkyscraperB",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "skyscraperC": {
    "path": "/content-browser/city/skyscraperC.glb",
    "thumbnail": "/content-browser/city/thumbnails/skyscraperC.png",
    "displayName": "SkyscraperC",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "skyscraperD": {
    "path": "/content-browser/city/skyscraperD.glb",
    "thumbnail": "/content-browser/city/thumbnails/skyscraperD.png",
    "displayName": "SkyscraperD",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "skyscraperE": {
    "path": "/content-browser/city/skyscraperE.glb",
    "thumbnail": "/content-browser/city/thumbnails/skyscraperE.png",
    "displayName": "SkyscraperE",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "skyscraperF": {
    "path": "/content-browser/city/skyscraperF.glb",
    "thumbnail": "/content-browser/city/thumbnails/skyscraperF.png",
    "displayName": "SkyscraperF",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "small_buildingA": {
    "path": "/content-browser/city/small_buildingA.glb",
    "thumbnail": "/content-browser/city/thumbnails/small_buildingA.png",
    "displayName": "Small BuildingA",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "small_buildingB": {
    "path": "/content-browser/city/small_buildingB.glb",
    "thumbnail": "/content-browser/city/thumbnails/small_buildingB.png",
    "displayName": "Small BuildingB",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "small_buildingC": {
    "path": "/content-browser/city/small_buildingC.glb",
    "thumbnail": "/content-browser/city/thumbnails/small_buildingC.png",
    "displayName": "Small BuildingC",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "small_buildingD": {
    "path": "/content-browser/city/small_buildingD.glb",
    "thumbnail": "/content-browser/city/thumbnails/small_buildingD.png",
    "displayName": "Small BuildingD",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "small_buildingE": {
    "path": "/content-browser/city/small_buildingE.glb",
    "thumbnail": "/content-browser/city/thumbnails/small_buildingE.png",
    "displayName": "Small BuildingE",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "small_buildingF": {
    "path": "/content-browser/city/small_buildingF.glb",
    "thumbnail": "/content-browser/city/thumbnails/small_buildingF.png",
    "displayName": "Small BuildingF",
    "type": "model",
    "modelType": "city",
    "hudModelRot": [
      0,
      0,
      0
    ]
  }
};
		