
// Generated by generateContentBrowserItems.js

/* eslint-disable import/no-anonymous-default-export */
export default {
  "Plate_Corner_01": {
    "path": "/content-browser/floor/Plate_Corner_01.glb",
    "thumbnail": "/content-browser/floor/thumbnails/Plate_Corner_01.png",
    "displayName": "Plate Corner 01",
    "type": "model",
    "modelType": "floor",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Plate_Curve_01": {
    "path": "/content-browser/floor/Plate_Curve_01.glb",
    "thumbnail": "/content-browser/floor/thumbnails/Plate_Curve_01.png",
    "displayName": "Plate Curve 01",
    "type": "model",
    "modelType": "floor",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Plate_Pavement_01": {
    "path": "/content-browser/floor/Plate_Pavement_01.glb",
    "thumbnail": "/content-browser/floor/thumbnails/Plate_Pavement_01.png",
    "displayName": "Plate Pavement 01",
    "type": "model",
    "modelType": "floor",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Plate_Road_01": {
    "path": "/content-browser/floor/Plate_Road_01.glb",
    "thumbnail": "/content-browser/floor/thumbnails/Plate_Road_01.png",
    "displayName": "Plate Road 01",
    "type": "model",
    "modelType": "floor",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Plate_Sidewalk_01": {
    "path": "/content-browser/floor/Plate_Sidewalk_01.glb",
    "thumbnail": "/content-browser/floor/thumbnails/Plate_Sidewalk_01.png",
    "displayName": "Plate Sidewalk 01",
    "type": "model",
    "modelType": "floor",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Plate_Wood_01": {
    "path": "/content-browser/floor/Plate_Wood_01.glb",
    "thumbnail": "/content-browser/floor/thumbnails/Plate_Wood_01.png",
    "displayName": "Plate Wood 01",
    "type": "model",
    "modelType": "floor",
    "hudModelRot": [
      0,
      0,
      0
    ]
  }
};
		