
// Generated by generateContentBrowserItems.js

/* eslint-disable import/no-anonymous-default-export */
export default {
  "Banner_01": {
    "path": "/content-browser/item/Banner_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Banner_01.png",
    "displayName": "Banner 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Lightpost_01": {
    "path": "/content-browser/item/Lightpost_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Lightpost_01.png",
    "displayName": "Lightpost 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Shield_Green_01": {
    "path": "/content-browser/item/Shield_Green_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Shield_Green_01.png",
    "displayName": "Shield Green 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Shield_Red_01": {
    "path": "/content-browser/item/Shield_Red_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Shield_Red_01.png",
    "displayName": "Shield Red 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Stairs_Stone_01": {
    "path": "/content-browser/item/Stairs_Stone_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Stairs_Stone_01.png",
    "displayName": "Stairs Stone 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Stairs_Wood_01": {
    "path": "/content-browser/item/Stairs_Wood_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Stairs_Wood_01.png",
    "displayName": "Stairs Wood 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Tree_01": {
    "path": "/content-browser/item/Tree_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Tree_01.png",
    "displayName": "Tree 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Wood_Railing_01": {
    "path": "/content-browser/item/Wood_Railing_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Wood_Railing_01.png",
    "displayName": "Wood Railing 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  },
  "Wood_Triangle_01": {
    "path": "/content-browser/item/Wood_Triangle_01.glb",
    "thumbnail": "/content-browser/item/thumbnails/Wood_Triangle_01.png",
    "displayName": "Wood Triangle 01",
    "type": "model",
    "modelType": "item",
    "hudModelRot": [
      0,
      0,
      0
    ]
  }
};
		